### ISSUE TITLE
当format的时候有两个％s时无法正确显示结果

### ISSUE THREAD

**Issue by skadilover** [bigpyer/ymtlog#1]
package main

import (
        "time"
        logger "ymtlog"
)

func main() {
        var str1 string
        str2 := "Err str2"
        logger.Info("err str1 is %s , err str2 is %s", str1, str2)
        time.Sleep(time.Second \* 3)
}

log 文件中的结果为：
2015/09/07 15:20:42.266153 [issuesYmtlog.go:11][INFO] err str1 is [ Err str2] , err str2 is %!s(MISSING)

**Comment by niubell** [comment]
已经更改了日志调用方式，这个问题也已经不存在。
